# Generated by Django 5.2.7 on 2025-10-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discount_percentage_product_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, null=True),
        ),
    ]
